ACTION_IF FILE_EXISTS_IN_GAME ~misc9q.itm~ THEN BEGIN // ToB

  // animation corrections
  COPY_EXISTING ~misc9q.itm~ ~override~
    WRITE_ASCII 0x22 "sc" #2

END

ACTION_IF GAME_IS ~tob bg2ee eet~ THEN BEGIN // ToB

  COPY_EXISTING ~sw1h66.itm~ ~override~
    WRITE_ASCII 0x22 "ss" #2

  COPY_EXISTING ~sw1h67.itm~ ~override~
    WRITE_ASCII 0x22 "s1" #2

  COPY_EXISTING ~sw1h68a.itm~ ~override~
    WRITE_ASCII 0x22 "sc" #2

END