DEFINE_ACTION_FUNCTION protect_sharteel BEGIN


      ACTION_FOR_EACH creature IN sharte sharte4 sharte6 BEGIN
         COPY_EXISTING "%tutu_var%%creature%.cre" override
            ADD_CRE_ITEM monhp1 #0 #0 #0 none RRING
         BUT_ONLY
      END

<<<<<<<< .../stratagems-inline/sharadd.baf
IF
	InParty(Myself)
	HasItem("monhp1",Myself)
THEN
	RESPONSE #100
		DestroyItem("monhp1")
END
>>>>>>>>

     LAF extend STR_VAR file= ~%tutu_scripts%harteel~ top=sharadd inline=yes END

END
